### ISSUE TITLE
Selecting the 80186 second processor can cause an abend

### ISSUE THREAD

**Issue by rjpontefract** [CommanderCoder/BeebEm#1]
Selecting the 80186 second processor can cause the CPU code to reference opcode_base before it has been initialised.  As the CPU code is running in a thread, it can attempt to execute i86 instructions before the i86 code has been initialised during the reset.

I worked around this issue by adding a cpu_suspended global variable which is checked for in Exec6502Instruction().  If it is set, it simply returns.    In the switch case 't186' the flag is set prior to setting the Tube186Enabled and cleared after the call to ResetBeebSystem().

I have a feeling that this isn't the real solution to this and somehow pausing the CPU thread on the dispatch queue might be a better option.  I looked into that but my C++ is better than my Swift, but I thought that maybe a DispatchSpecificKey could be employed.  

I certainly welcome your thoughts on how to to do this better as it may be useful to suspend the CPU during reset for other reasons as well.

**Comment by CommanderCoder** [comment]
There is no particular reason to run the CPU on a separate thread.  I've put the CPU update back on the main thread.  Perhaps that will fix it.

**Comment by rjpontefract** [comment]
Looks a lot better now, thanks.
