### ISSUE TITLE
Missing features: screenshots?

### ISSUE THREAD

**Issue by Shrapnel21** [CommanderCoder/BeebEm#3]
Hi everyone!
The description says some features are still missing: is the 'screenshot' command one of those? Or am I missing something?
But anyway, thank you very much for this updated version of BeebEm. Please keep up the good work! =)

**Comment by CommanderCoder** [comment]
I've added screenshot saving - it puts the file into the Pictures folder with a timestamp as the filename.

**Comment by Shrapnel21** [comment]
Thank you very much, can't wait to get the new version! =)
