### ISSUE TITLE
BeebEm is 'damaged'

### ISSUE THREAD

**Issue by JudgeBeeb** [CommanderCoder/BeebEm#4]
MacOS Monterey 12.5 on an M1 MacBook Pro. I installed the app using the DMG file. When launching the app, MacOS reported that it was 'damaged' and needed to be deleted. No problems with the version in the zip file.

**Comment by franton** [comment]
There's actually a couple things wrong here. One of which I can fix on my own, the other not so much.

Issue 1: the quarantine extended attribute is set on the app bundle.
`me@mac  ~  xattr /Applications/BeebEmMac-5/BeebEm5.app 
com.apple.quarantine
`

Issue 2: the signing is broken. Here's the output from Patrick Wardle's "whatsyoursign" utility. (https://objective-see.org/products/whatsyoursign.html)

<img width="804" alt="image" src="https://user-images.githubusercontent.com/5807892/182035980-a93f2384-8078-4597-9b16-1572414eece0.png">

While it's possible for me to fix the quarantine attribute stuff, the codesigning and notarization of the app bundle unfortunately needs work.

**Comment by franton** [comment]
Confirmed. I was able to build and sign with my own developer account and the issue goes away. However that's good as a test, but nothing I should ever be distributing.

**Comment by CommanderCoder** [comment]
I had a look at tidying up the distribution.  I don't have an apple developer account so I can't sign the app.  All attributes are cleared from the APP in the zip file.  The DMG and zip file are basically the same but the DMG can be mounted.

#

**Comment by franton** [comment]
Yes the .zip process will be stripping the extended attributes from the .app bundle but the .dmg (as a disk image) will not. Your packaging process should ideally execute something like:

`xattr -cr /path/to/BeebEm5.app`

**Comment by CommanderCoder** [comment]
create-distribution.zsh does this step.  Please check using the new version in [beebem-mac](https://github.com/CommanderCoder/beebem-mac/releases)
