### ISSUE TITLE
Lock-up after using the menu after .dmg installation

### ISSUE THREAD

**Issue by joeb1234567** [CommanderCoder/BeebEm#5]
I have been trying to build this on an M1 Pro Mac using Xcode 15.1 on macOS Sonoma 14.2.

Everything seems fine when I run it directly from Xcode - I can use the menu to load disc images and execute them without problem. However, when I create a .dmg file (using 'create-distribution.zsh') and install it, the resulting BeebEm seems to lock-up after I interact with the menu.

For example, directly after launching the emulator I see the normal "BBC Computer 32K" output and a flashing cursor. If I click on "File | Load Disc 0" and then click "Cancel", the machine seems unresponsive, I no longer have a flashing cursor and the emulator process is using 115% CPU (prior to using the menu it was using 35% CPU). The same thing seems to happen with other menu items, however, it seems that I can enable the joystick without problem.

It seems likely that I've done something wrong with the way I generated the .dmg file, although I followed the README instructions as closely as I could. I also haven't managed to find a way to get debug output from the .dmg installed version of the emulator (and as I said, running it from Xcode seems to work fine). Any pointers would be gratefully received.

Thanks.

**Comment by CommanderCoder** [comment]
Please try again with the new version at [beebem-mac](https://github.com/CommanderCoder/beebem-mac/releases).
