### ISSUE TITLE
Saved States not working on Mac Sonoma 14.2.1?

### ISSUE THREAD

**Issue by AndrewMacUser** [CommanderCoder/BeebEm#6]
Hi, I've always been very impressed with BeebEm and delighted and grateful to see an update V5 for newer Macs. While it works fine in every other respect on my Mac Book Air 2020, it doesn't seem able to save states. I was just wondering if I was doing something wrong or if it was a feature that does not work in this version at this time? When I click on save state, you can choose a location and a file name, but then it just doesn't appear to do anything. No file is saved, no error message. Many thanks for reading this comment, thank you, it's a terrific emulator.

**Comment by CommanderCoder** [comment]
Please test again using the newer version at [beebem-mac](https://github.com/CommanderCoder/beebem-mac/releases)
